add_newline = true
command_timeout = 200
#format = "[$directory$git_branch$git_status$kubernetes$python]($style)$character"


[character]
error_symbol = "[âœ—](bold cyan)"
success_symbol = "[â¯](bold cyan)"

[directory]
truncation_length = 2
truncation_symbol = "â€¦/"
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style) "
style = "italic cyan"

[git_status]
format     = '[$all_status]($style)'
style      = "cyan"
ahead      = "â‡¡${count} "
diverged   = "â‡•â‡¡${ahead_count}â‡£${behind_count} "
behind     = "â‡£${count} "
conflicted = "î®« "
up_to_date = "ï€Œ "
untracked  = "? "
modified   = "î©± "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""

# Add at end of file:
[python]
symbol = "ğŸ "
pyenv_version_name = false
format = 'via [${symbol}(${version} )]($style)'
style = "bold yellow"
python_binary = ["python3", "python"]
detect_extensions = ["py"]
detect_files = [".python-version", "Pipfile", "pyproject.toml", "requirements.txt", "setup.py", "tox.ini"]
detect_folders = []
disabled = false

[gcloud]
disabled = true

[kubernetes]
format = 'on [$symbol$context \($namespace\)]($style) '
disabled = false

# Matches "toolsense-iot-dev"
[[kubernetes.contexts]]
context_pattern = ".*-iot-dev"
symbol = "ğŸ’¥ "
context_alias = "IoT"

# Matches "toolsense-iot"
[[kubernetes.contexts]]
context_pattern = ".*-iot"
symbol = "âš™ï¸ "
context_alias = "IoT"

# Matches "toolsense-dev"
[[kubernetes.contexts]]
context_pattern = ".*-dev"
symbol = "ğŸ’¥ "
context_alias = "FE"

# Matches "toolsense"
[[kubernetes.contexts]]
context_pattern = "toolsense"
symbol = "âš™ï¸ "
context_alias = "FE"
